config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do 
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status:  { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
  
  belongs_to :topic

  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [
    :show, :edit, :update, :destroy, :toggle_status
  ]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status ]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "My Portifolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.topic = Topic.last

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post is live' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Your post was updated' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Your post was removed' }
    end
  end

  def toggle_status
    @blog.published? ? @blog.draft! : @blog.published!
    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"> <%= link_to blog.title, blog  %> </h2>
  <p class="blog-post-meta"><%= distance_of_time_in_words(blog.created_at, Time.now) + ' ago' %></p>

  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog) %> /
      <%= link_to 'Edit', edit_blog_path(blog) %> /
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

  <p>
  <%= blog.body %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body, class: "form-control", rows: 10 %> </div>

  <div class="form-group">
    <%= form.submit "Create Post", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

    <%= paginate @blogs %>

    <%= render @blogs %>

    <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

    <h2><%= @blog.title %></h2>
    <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>

    <p>
      <%= @blog.body %>
    </p>

  <nav class="blog-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
  </nav>
</div>