config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do 
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  includes Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
   order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [
    :show, :destroy, :edit, :update
  ]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|    
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end
  
  def angular
    @angular_portfolio_items = Portfolio.angular
  end
  
  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
      @portfolio_item = Portfolio.new(portfolio_params)

      respond_to do |format|
        if @portfolio_item.save
          format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live." }
        else
          format.html { render :new }
        end
      end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Your portfolio was updated." }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end
  
  def destroy
    @portfolio_item.destroy
    redirect_to portfolios_url, notice: "Portifolio was removed."
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                     )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 10 %>
      </div>
    </div>
  </div>

  <hr>

  <h2>Technologies Used:</h2>
  <div>
    <%= f.fields_for :technologies do |technology_form| %> 
      <div class="form-group">
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: "form-control" %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit portfolio_item.new_record? ? "Create Portfolio" : "Update Portfolio", class: "btn btn-primary btn-block" %>
  </div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="portfolio-card col-md-4" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 box-shadow">
    <%= image_tag(portfolio_item.thumb_image, class:"card-img-top") unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <span><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>
      <p class="card-text"><%= portfolio_item.subtitle %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
          <%= link_to "Delete", portfolio_item, class: "btn btn-sm btn-outline-secondary", method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>
        </div>
        <small class="text-muted">
          <%= distance_of_time_in_words(portfolio_item.created_at, Time.now) + ' ago' %>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <h2><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item)  if logged_in?(:site_admin) %>
  </p>
  <p>
  <%= link_to "Delete Portfolio", portfolio_item, method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>
  </p>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<!-- <%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %> -->

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
        <%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>
    </div>
    <div class="col-md-5">
        <h1><%= @portfolio_item.title %></h1>

        <hr>

        <em><%= @portfolio_item.subtitle %></em>

        <p><%= @portfolio_item.body %></p>

        <hr>

        <h3>Technologies Used:</h3>

        <% @portfolio_item.technologies.each do |t| %>
          <p><%= t.name %></p>
        <% end %>

        <p>
        <%= link_to "Delete Portfolio", @portfolio_item, method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>
        </p>
    </div>
  </div>
</div>